/* Process PRX parameters emitted by the official SDK 4.75 ABI. */

   .align 2
   .section ".lib.ent","a"

   .align 2
   .section ".lib.stub","a"

   .align 2
   .section ".sys_proc_prx_param","a"
   .long 0x40
   .long 0x1b434cec
   .long 4
   .long 0x00475001
   .long __libentstart
   .long __libentend
   .long __libstubstart
   .long __libstubend
   .short 0x0101
   .short 0
   .long 0
   .long 0
   .long 0
   .long 0
   .long 0
   .long 0
   .long 0
