#pragma once

#include <io/pad.h>

typedef padData CellPadData;

#define CELL_PAD_CTRL_LEFT     PAD_CTRL_LEFT
#define CELL_PAD_CTRL_DOWN     PAD_CTRL_DOWN
#define CELL_PAD_CTRL_RIGHT    PAD_CTRL_RIGHT
#define CELL_PAD_CTRL_UP       PAD_CTRL_UP
#define CELL_PAD_CTRL_START    PAD_CTRL_START
#define CELL_PAD_CTRL_R3       PAD_CTRL_R3
#define CELL_PAD_CTRL_L3       PAD_CTRL_L3
#define CELL_PAD_CTRL_SELECT   PAD_CTRL_SELECT
#define CELL_PAD_CTRL_SQUARE   PAD_CTRL_SQUARE
#define CELL_PAD_CTRL_CROSS    PAD_CTRL_CROSS
#define CELL_PAD_CTRL_CIRCLE   PAD_CTRL_CIRCLE
#define CELL_PAD_CTRL_TRIANGLE PAD_CTRL_TRIANGLE
#define CELL_PAD_CTRL_R1       PAD_CTRL_R1
#define CELL_PAD_CTRL_L1       PAD_CTRL_L1
#define CELL_PAD_CTRL_R2       PAD_CTRL_R2
#define CELL_PAD_CTRL_L2       PAD_CTRL_L2

#define CELL_PAD_BTN_OFFSET_DIGITAL1       PAD_BUTTON_OFFSET_DIGITAL1
#define CELL_PAD_BTN_OFFSET_DIGITAL2       PAD_BUTTON_OFFSET_DIGITAL2
#define CELL_PAD_BTN_OFFSET_ANALOG_RIGHT_X PAD_BUTTON_OFFSET_ANALOG_RIGHT_X
#define CELL_PAD_BTN_OFFSET_ANALOG_RIGHT_Y PAD_BUTTON_OFFSET_ANALOG_RIGHT_Y
#define CELL_PAD_BTN_OFFSET_ANALOG_LEFT_X  PAD_BUTTON_OFFSET_ANALOG_LEFT_X
#define CELL_PAD_BTN_OFFSET_ANALOG_LEFT_Y  PAD_BUTTON_OFFSET_ANALOG_LEFT_Y

#define cellPadInit    ioPadInit
#define cellPadGetData ioPadGetData
#define cellPadEnd     ioPadEnd
